import React from "react";

export default function Collection() {
  return (
    <div className="mt-28  pb-5 block mx-auto w-[85%]">
      <div className=" lg:w-[20%]">
        <p className="text-4xl text-black/80 font-bold">
          The community Showcase
        </p>
        <p className="mt-2 font-[600] text-gray-500/80">
          Browse through collection of imaginative and visually stunnig images
          generated by DALL-E AI
        </p>
      </div>
      
    </div>
  );
}
